#!/Library/Frameworks/Python.framework/Versions/3.6/bin/python3

import sys
from lib.utils.rm_color_manager import *
from lib.utils.rm_opt_manager import *
from lib.utils.rm_script_manager import *
import getopt

optionTest = RMOption("t", "test", False, "this is a Test Description")
optionValue = RMOption("v", "value", True, "this is a Test Description with Value")

options = [optionTest, optionValue]
optionManager = RMOptManager(options)

def main():
	checkVersionAndArguments()
	
	if optionManager.argumentExist(optionTest):
		print("test Exist")

def checkVersionAndArguments():
	global options, optionManager
	RMScriptManager.checkVersion((3,6), "Please use Python 3.6 or greater!")
	optionManager.checkArguments()
	
if __name__ == '__main__':
	main()